### ISSUE TITLE
Find and Upload  Persian Weblog Corpus

### ISSUE THREAD

**Issue by sehsanm** [sehsanm/embedding-benchmark#2]
*  Find the Persian Weblog Corpus 
*  Define a  corpus file standard. (To be discussed with other Corpus builders) - Most probably one sentence in each line  (Talk to owner of #1 ) 
*  Upload the  zipped version of the corpus in S3 bucket (Contact @sehsanm  to get the access details)

**Comment by Sahand504** [comment]
I could provide irBlogs for this issue.
Please invite me so I can assign this task to myself.

**Comment by sehsanm** [comment]
@Sahand504  Please update readme.md to point to irBlog page

**Comment by sehsanm** [comment]
Just a reminder!

**Comment by sehsanm** [comment]
Another Reminder!

**Comment by sehsanm** [comment]
Thanks
