### ISSUE TITLE
I can't download corpus

### ISSUE THREAD

**Issue by abb4s** [sehsanm/embedding-benchmark#54]
hey I want to build fasttext model . and I need to download our corpora. but I get this error page :

"That didn't work
We're sorry, but abbas.hoseini74@gmail.com can't be found in the sbuacir-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you. "

**Comment by sehsanm** [comment]
Hi Abbas
I updated the links please check now and if it works fine, please close the
issue.
Ehsan

**Comment by abb4s** [comment]
hi ,  thank you.
